### ISSUE TITLE
Cannot read property 'toLowerCase'

### ISSUE THREAD

**Issue by virtueistheonlygood** [CryptoMF/frostybot-js#102]
Hi guys,

I'm getting the following exception while running: frostybot trade:ftxmain:buy symbol=ETHUSD price=-5%
The symbol ETHUSD has a default size, take profit and profit size defined on the Pair-Level Settings.

What could be causing this issue?

```
{
  "result": "success",
  "type": "boolean",
  "data": false,
  "messages": [
    "2021-12-12 01:58:28 | WARNING | Unhandled Exception: TypeError: Cannot read property 'toLowerCase' of undefined at frostybot_trade_module.potential_position (mod.trade.js:1275:41)",
    "2021-12-12 01:58:28 | NOTICE  | Command Completed: Execution Time: 10.338 seconds"
  ]
}

LogViewer:

2021-12-12T02:05:04.000Z │ DEBUG   │ Order size provided in USD (USD size)
2021-12-12T02:05:04.000Z │ NOTICE  │ Current position USD size is: USD 0
2021-12-12T02:05:04.000Z │ NOTICE  │ Target position USD size is: USD 1000
2021-12-12T02:05:04.000Z │ NOTICE  │ Order required to reach target: Buy => USD 1000
2021-12-12T02:05:05.000Z │ DEBUG   │ Size provided in USD on a stablecoin-paired asset. Using USD size as quote size.
2021-12-12T02:05:05.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to ETH (0.26085141903171954)
2021-12-12T02:05:05.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USD, type: limit, side: buy, amount: 0.260, price: 3833.6, params: {}}
2021-12-12T02:05:05.000Z │ NOTICE  │ Order added to queue:
2021-12-12T02:05:05.000Z │ NOTICE  │   ├─ symbol: ETH/USD
2021-12-12T02:05:05.000Z │ NOTICE  │   ├─ type:   limit
2021-12-12T02:05:05.000Z │ NOTICE  │   ├─ side:   buy
2021-12-12T02:05:05.000Z │ NOTICE  │   ├─ amount: 0.260
2021-12-12T02:05:05.000Z │ NOTICE  │   └─ price:  3833.6
2021-12-12T02:05:07.000Z │ DEBUG   │ Take profit size not provided, using default take profit size: ftxmain:eth/usd:defprofitsize=70%
**2021-12-12T02:05:07.000Z │ DEBUG   │ Take profit not provided, using default take profit: ftxmain:eth/usd:defprofittrigger=15%
2021-12-12T02:05:09.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'toLowerCase' of undefined at frostybot_trade_module.potential_position (mod.trade.js:1275:41)
2021-12-12T02:05:09.000Z │ NOTICE  │ Command Completed: Execution Time: 12.263 seconds**



2021-12-12T01:58:28.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'toLowerCase' of undefined at frostybot_trade_module.potential_position (mod.trade.js:1275:41)
```

 core/mod.trade.js:1275

        // Get pending limit orders and add to possible average position entry price
        var orders = await this.exchange_execute(stub, 'orders', {status: 'open', symbol: symbol, type: 'limit'}, true);
        for (var i = 0; i < orders.length; i++) {
            var order = orders[i];
            if (!side && order.direction !== false)  side = dirmap[order.side.toLowerCase()];
            levels.push({
                price: order.price,
                base: order.size_base,
                quote: order.size_quote,
                amount: order_sizing == 'base' ? order.size_base : order.size_quote,
                **side: dirmap[order.side.toLowerCase()],**
                type: 'orders'
            });
        };

**Comment by virtueistheonlygood** [comment]
I've removed the line 1275 from core/mod.trade.js -for testing purposes- and it works fine: 
frostybot trade:ftxmain:buy symbol=ETHUSD price=-5%,7%,3, 



```
2021-12-12T02:17:17.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to ETH (0.08677391923083597)
2021-12-12T02:17:17.000Z │ DEBUG   │ Converted order parameters into 3 layered orders between 3760.5 and 3841.4
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USD, type: limit, side: buy, amount: 0.088, price: 3760.5, params: {}}
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue:
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ symbol: ETH/USD
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ type:   limit
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ side:   buy
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ amount: 0.088
2021-12-12T02:17:17.000Z │ NOTICE  │   └─ price:  3760.5
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USD, type: limit, side: buy, amount: 0.087, price: 3800.9, params: {}}
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue:
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ symbol: ETH/USD
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ type:   limit
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ side:   buy
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ amount: 0.087
2021-12-12T02:17:17.000Z │ NOTICE  │   └─ price:  3800.9
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USD, type: limit, side: buy, amount: 0.086, price: 3841.4, params: {}}
2021-12-12T02:17:17.000Z │ NOTICE  │ Order added to queue:
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ symbol: ETH/USD
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ type:   limit
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ side:   buy
2021-12-12T02:17:17.000Z │ NOTICE  │   ├─ amount: 0.086
2021-12-12T02:17:17.000Z │ NOTICE  │   └─ price:  3841.4
2021-12-12T02:17:20.000Z │ DEBUG   │ Take profit size not provided, using default take profit size: ftxmain:eth/usd:defprofitsize=70%
2021-12-12T02:17:20.000Z │ DEBUG   │ Take profit not provided, using default take profit: ftxmain:eth/usd:defprofittrigger=15%
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: SAND/USD
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: AXS/USD
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: FTT/USD
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: KIN/USD
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: 1INCH/USD
2021-12-12T02:17:22.000Z │ DEBUG   │ Converting using symbol: EUR/USD
2021-12-12T02:17:23.000Z │ DEBUG   │ Current position and open orders calculated to potential position: {price: 3800.6233716475094, base: 0.261, quote: 991.9627, sizing: base, side: buy, amount: 0.261, totals: {position: false, orders: false, queue: 0.261}}
2021-12-12T02:17:23.000Z │ DEBUG   │ Current position and open orders calculated to potential position:
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ price:  3800.6233716475094
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ base:   0.261
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ quote:  991.9627
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ sizing: base
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ side:   buy
2021-12-12T02:17:23.000Z │ DEBUG   │   ├─ amount: 0.261
2021-12-12T02:17:23.000Z │ DEBUG   │   └─ totals: {position: false, orders: false, queue: 0.261}
2021-12-12T02:17:23.000Z │ DEBUG   │ Converted relative price: 3800.6+15% => 4370.7
2021-12-12T02:17:26.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to ETH (0.1827)
2021-12-12T02:17:26.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USD, type: takeProfit, side: sell, amount: 0.182, params: {reduceOnly: true, triggerPrice: 4370.7}}
2021-12-12T02:17:26.000Z │ NOTICE  │ Order added to queue:
2021-12-12T02:17:26.000Z │ NOTICE  │   ├─ symbol: ETH/USD
2021-12-12T02:17:26.000Z │ NOTICE  │   ├─ type:   takeProfit
2021-12-12T02:17:26.000Z │ NOTICE  │   ├─ side:   sell
2021-12-12T02:17:26.000Z │ NOTICE  │   ├─ amount: 0.182
2021-12-12T02:17:26.000Z │ NOTICE  │   └─ params: {reduceOnly: true, triggerPrice: 4370.7}
2021-12-12T02:17:27.000Z │ DEBUG   │ Order submitted to exchange: 104152719078
2021-12-12T02:17:27.000Z │ DEBUG   │ Order submission doublecheck enabled for exchange, checking order: 104152719078
2021-12-12T02:17:31.000Z │ NOTICE  │ Double-checked that order was created on exchange: 104152719078
2021-12-12T02:17:31.000Z │ SUCCESS │ Order submitted successfully: {stub: ftxmain, symbol: ETH/USD, type: limit, side: buy, amount: 0.088, price: 3760.5, params: {}}
2021-12-12T02:17:31.000Z │ SUCCESS │ Order submitted successfully:
2021-12-12T02:17:31.000Z │ SUCCESS │   ├─ stub:   ftxmain
2021-12-12T02:17:31.000Z │ SUCCESS │   ├─ symbol: ETH/USD
2021-12-12T02:17:31.000Z │ SUCCESS │   ├─ type:   limit
2021-12-12T02:17:31.000Z │ SUCCESS │   ├─ side:   buy
2021-12-12T02:17:31.000Z │ SUCCESS │   ├─ amount: 0.088
2021-12-12T02:17:31.000Z │ SUCCESS │   └─ price:  3760.5
2021-12-12T02:17:32.000Z │ DEBUG   │ Order submitted to exchange: 104152729103
2021-12-12T02:17:32.000Z │ DEBUG   │ Order submission doublecheck enabled for exchange, checking order: 104152729103
2021-12-12T02:17:36.000Z │ NOTICE  │ Double-checked that order was created on exchange: 104152729103
2021-12-12T02:17:36.000Z │ SUCCESS │ Order submitted successfully: {stub: ftxmain, symbol: ETH/USD, type: limit, side: buy, amount: 0.087, price: 3800.9, params: {}}
2021-12-12T02:17:36.000Z │ SUCCESS │ Order submitted successfully:
2021-12-12T02:17:36.000Z │ SUCCESS │   ├─ stub:   ftxmain
2021-12-12T02:17:36.000Z │ SUCCESS │   ├─ symbol: ETH/USD
2021-12-12T02:17:36.000Z │ SUCCESS │   ├─ type:   limit
2021-12-12T02:17:36.000Z │ SUCCESS │   ├─ side:   buy
2021-12-12T02:17:36.000Z │ SUCCESS │   ├─ amount: 0.087
2021-12-12T02:17:36.000Z │ SUCCESS │   └─ price:  3800.9
2021-12-12T02:17:37.000Z │ DEBUG   │ Order submitted to exchange: 104152747506
2021-12-12T02:17:37.000Z │ DEBUG   │ Order submission doublecheck enabled for exchange, checking order: 104152747506
2021-12-12T02:17:41.000Z │ NOTICE  │ Double-checked that order was created on exchange: 104152747506
2021-12-12T02:17:41.000Z │ SUCCESS │ Order submitted successfully: {stub: ftxmain, symbol: ETH/USD, type: limit, side: buy, amount: 0.086, price: 3841.4, params: {}}
2021-12-12T02:17:41.000Z │ SUCCESS │ Order submitted successfully:
2021-12-12T02:17:41.000Z │ SUCCESS │   ├─ stub:   ftxmain
2021-12-12T02:17:41.000Z │ SUCCESS │   ├─ symbol: ETH/USD
2021-12-12T02:17:41.000Z │ SUCCESS │   ├─ type:   limit
2021-12-12T02:17:41.000Z │ SUCCESS │   ├─ side:   buy
2021-12-12T02:17:41.000Z │ SUCCESS │   ├─ amount: 0.086
2021-12-12T02:17:41.000Z │ SUCCESS │   └─ price:  3841.4
2021-12-12T02:17:41.000Z │ DEBUG   │ Order submitted to exchange: 115375547
2021-12-12T02:17:41.000Z │ DEBUG   │ Order submission doublecheck enabled for exchange, checking order: 115375547
2021-12-12T02:17:46.000Z │ NOTICE  │ Double-checked that order was created on exchange: 115375547
2021-12-12T02:17:46.000Z │ SUCCESS │ Order submitted successfully: {stub: ftxmain, symbol: ETH/USD, type: takeProfit, side: sell, amount: 0.182, params: {reduceOnly: true, triggerPrice: 4370.7}}
2021-12-12T02:17:46.000Z │ SUCCESS │ Order submitted successfully:
2021-12-12T02:17:46.000Z │ SUCCESS │   ├─ stub:   ftxmain
2021-12-12T02:17:46.000Z │ SUCCESS │   ├─ symbol: ETH/USD
2021-12-12T02:17:46.000Z │ SUCCESS │   ├─ type:   takeProfit
2021-12-12T02:17:46.000Z │ SUCCESS │   ├─ side:   sell
2021-12-12T02:17:46.000Z │ SUCCESS │   ├─ amount: 0.182
2021-12-12T02:17:46.000Z │ SUCCESS │   └─ params: {reduceOnly: true, triggerPrice: 4370.7}
2021-12-12T02:17:46.000Z │ NOTICE  │ Processed order queue: 4/4 order(s) submitted successfully.
2021-12-12T02:17:46.000Z │ NOTICE  │ Command Completed: Execution Time: 41.488 seconds
```

**Comment by virtueistheonlygood** [comment]
The issue is related with the default take profit, calculated from the 2nd buy limit order instead of the actual price.
