### ISSUE TITLE
FrostyBot sends too many requests to exchange resulting in IP ban

### ISSUE THREAD

**Issue by fireblade-au** [CryptoMF/frostybot-js#67]
Not sure why this happened but FrostyBot did not behave nicely with Binance and resulted in a IP ban.

Code needs to be checked why it is sending too many requests and FrostyBot needs to ensure API calls do not exceed the exchange protection mechanisms.

![image](https://user-images.githubusercontent.com/83438779/118059349-af923c80-b3d3-11eb-9c45-52a44a9f2d0b.png)

**Comment by fireblade-au** [comment]
This occurred after attempted buy orders which were not successful as they are not seen in the order history.
FrostyBot appears to have tried to roll-back the two orders in question resulting in Binances DDoS protection kicking in and banned the server IP address (sigh). 

2021-05-13T06:05:09.000Z │ NOTICE  │ Current position base size is: ETH 0
2021-05-13T06:05:09.000Z │ NOTICE  │ Target position base size is: ETH 2
2021-05-13T06:05:09.000Z │ NOTICE  │ Order required to reach target: Buy => ETH 2
2021-05-13T06:05:12.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to ETH (2)
2021-05-13T06:05:14.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USDT, type: MARKET, side: buy, amount: 1.99999, params: {}}
2021-05-13T06:05:14.000Z │ NOTICE  │ Order added to queue:
2021-05-13T06:05:14.000Z │ NOTICE  │   ├─ symbol: ETH/USDT
2021-05-13T06:05:14.000Z │ NOTICE  │   ├─ type:   MARKET
2021-05-13T06:05:14.000Z │ NOTICE  │   ├─ side:   buy
2021-05-13T06:05:14.000Z │ NOTICE  │   └─ amount: 1.99999
2021-05-13T06:05:17.000Z │ DEBUG   │ Current position size in USD: 5836.32
2021-05-13T06:05:17.000Z │ DEBUG   │ Current available balance in USD[removed]
2021-05-13T06:05:19.000Z │ DEBUG   │ Order size provided in BNB (base size)
2021-05-13T06:05:19.000Z │ NOTICE  │ Current position base size is: BNB 10.32164588
2021-05-13T06:05:19.000Z │ NOTICE  │ Target position base size is: BNB 13.32164588
2021-05-13T06:05:19.000Z │ NOTICE  │ Order required to reach target: Buy => BNB 3
2021-05-13T06:05:20.000Z │ DEBUG   │ Take profit size not provided, using default take profit size: binance-main:defprofitsize=50%
2021-05-13T06:05:22.000Z │ DEBUG   │ Take profit not provided, using default take profit: binance-main:defprofittrigger=100%
2021-05-13T06:05:23.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to BNB (3)
2021-05-13T06:05:25.000Z │ NOTICE  │ Order added to queue: {symbol: BNB/USDT, type: MARKET, side: buy, amount: 3.0000, params: {}}
2021-05-13T06:05:25.000Z │ NOTICE  │ Order added to queue:
2021-05-13T06:05:25.000Z │ NOTICE  │   ├─ symbol: BNB/USDT
2021-05-13T06:05:25.000Z │ NOTICE  │   ├─ type:   MARKET
2021-05-13T06:05:25.000Z │ NOTICE  │   ├─ side:   buy
2021-05-13T06:05:25.000Z │ NOTICE  │   └─ amount: 3.0000
2021-05-13T06:05:27.000Z │ WARNING │ Unhandled Exception: DDoSProtection: binance 429 Too Many Requests {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API."} at binance.handleErrors (binance.js:2642:19)
2021-05-13T06:05:28.000Z │ DEBUG   │ Current position and open orders calculated to potential position: {price: 3634.52, base: 1.99999, quote: 7269.0036548, sizing: base, side: buy, amount: 1.99999, totals: {position: false, orders: false, queue: 1.99999}}
2021-05-13T06:05:28.000Z │ DEBUG   │ Current position and open orders calculated to potential position:
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ price:  3634.52
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ base:   1.99999
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ quote:  7269.0036548
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ sizing: base
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ side:   buy
2021-05-13T06:05:28.000Z │ DEBUG   │   ├─ amount: 1.99999
2021-05-13T06:05:28.000Z │ DEBUG   │   └─ totals: {position: false, orders: false, queue: 1.99999}
2021-05-13T06:05:28.000Z │ DEBUG   │ Converted relative price: 3634.52+100% => 7269.04
2021-05-13T06:05:32.000Z │ WARNING │ Unhandled Exception: DDoSProtection: binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1620864452368. Please use the websocket for live updates to avoid bans."} at binance.handleErrors (binance.js:2642:19)
2021-05-13T06:05:36.000Z │ DEBUG   │ Current position and open orders calculated to potential position: {price: 565.4449999999999, base: 3, quote: 1696.3349999999998, sizing: base, side: buy, amount: 3, totals: {position: false, orders: false, queue: 3}}
2021-05-13T06:05:36.000Z │ DEBUG   │ Current position and open orders calculated to potential position:
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ price:  565.4449999999999
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ base:   3
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ quote:  1696.3349999999998
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ sizing: base
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ side:   buy
2021-05-13T06:05:36.000Z │ DEBUG   │   ├─ amount: 3
2021-05-13T06:05:36.000Z │ DEBUG   │   └─ totals: {position: false, orders: false, queue: 3}
2021-05-13T06:05:36.000Z │ DEBUG   │ Converted relative price: 565.44+100% => 1130.88
2021-05-13T06:05:37.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to ETH (0.999995)
2021-05-13T06:05:38.000Z │ NOTICE  │ Order added to queue: {symbol: ETH/USDT, type: TAKE_PROFIT, side: sell, amount: 0.99999, params: {reduceOnly: true, stopPrice: 7269.04}}
2021-05-13T06:05:38.000Z │ NOTICE  │ Order added to queue:
2021-05-13T06:05:38.000Z │ NOTICE  │   ├─ symbol: ETH/USDT
2021-05-13T06:05:38.000Z │ NOTICE  │   ├─ type:   TAKE_PROFIT
2021-05-13T06:05:38.000Z │ NOTICE  │   ├─ side:   sell
2021-05-13T06:05:38.000Z │ NOTICE  │   ├─ amount: 0.99999
2021-05-13T06:05:38.000Z │ NOTICE  │   └─ params: {reduceOnly: true, stopPrice: 7269.04}
2021-05-13T06:05:39.000Z │ WARNING │ Order submission failed: DDoSProtection: binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1620864452368. Please use the websocket for live updates to avoid bans."}
2021-05-13T06:05:39.000Z │ WARNING │ Order submission failed:

**Comment by CryptoMF** [comment]
Hi

Binance change their API weighting and as such you can baleful touch their
API without being rate limited. We have already made a fix for this in the
dev channel using websockets. It's much faster too (<1 sec) to place an
order.

It's dev, so it might be a little rough, but it definitely works well for
the few users who are testing it.

**Comment by fireblade-au** [comment]
Another FrostyBot failure?  I'm switching back to 3Commas as losing great entries.

![image](https://user-images.githubusercontent.com/83438779/118118466-5278a400-b430-11eb-8ee5-be779f54a6b1.png)

**Comment by CryptoMF** [comment]
I can't really see from your screenshot what failure you're referring to,
if you could share the log it would be more helpful.

We have traders trading very large accounts on Binance quite happily. And I
have referred you to the websocket version in dev, itself also being used
on very large accounts without issues. Have you tried it yet? It is a vast
improvement over the current stable version, and quite easy to switch to
using the "frostybot branch development" command.

If you would prefer to go back to 3commas, that's fine, but I would
appreciate it if you could at least share the log so that I can try and
isolate the issue for other users.

**Comment by shimuldn** [comment]
@fireblade-au 
For now you can just user development branch to fix the issue.
`git checkout development`
Than do the remaining setup.

**Comment by alperoguz** [comment]
Hello,

I faced this error on Bitmex testnet today. I was testing only with one small LTCUSD order.

2021-07-20T17:57:40.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:40.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...

You can find full log below.

`2021-07-20T17:57:16.000Z │ NOTICE  │ Whitelist verification is enabled
2021-07-20T17:57:16.000Z │ NOTICE  │ API Access Granted: 127.0.0.1 is whitelisted
2021-07-20T17:57:16.000Z │ NOTICE  │ Command Parameters: {command: trade:long, symbol: LTC/USD, size: 5, stub: bitmex_testnet}
2021-07-20T17:57:16.000Z │ NOTICE  │ Command Parameters:
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ command: trade:long
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ symbol:  LTC/USD
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ size:    5
2021-07-20T17:57:16.000Z │ NOTICE  │   └─ stub:    bitmex_testnet
2021-07-20T17:57:19.000Z │ NOTICE  │ Current position USD size is: USD 0
2021-07-20T17:57:19.000Z │ NOTICE  │ Target position USD size is: USD 5
2021-07-20T17:57:19.000Z │ NOTICE  │ Order required to reach target: Buy => USD 5
2021-07-20T17:57:21.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Market, side: buy, amount: 5, params: {execInst: }}
2021-07-20T17:57:21.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ type:   Market
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ side:   buy
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:21.000Z │ NOTICE  │   └─ params: {execInst: }
2021-07-20T17:57:24.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:25.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Stop, side: sell, amount: 5, params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}}
2021-07-20T17:57:25.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ type:   Stop
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ side:   sell
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:25.000Z │ NOTICE  │   └─ params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}
2021-07-20T17:57:28.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Limit, side: sell, amount: 5, price: 141.67, params: {undefined: 141.67}}
2021-07-20T17:57:28.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ type:   Limit
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ side:   sell
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ price:  141.67
2021-07-20T17:57:28.000Z │ NOTICE  │   └─ params: {undefined: 141.67}
2021-07-20T17:57:29.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:29.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:29.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:29.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...
2021-07-20T17:57:39.000Z │ WARNING │ Retrying order (Retry 1 of 5)...
2021-07-20T17:57:39.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Market, side: buy, amount: 5, params: {execInst: }}
2021-07-20T17:57:39.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ type:   Market
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ side:   buy
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:39.000Z │ SUCCESS │   └─ params: {execInst: }
2021-07-20T17:57:40.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Stop, side: sell, amount: 5, params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}}
2021-07-20T17:57:40.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ type:   Stop
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ side:   sell
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:40.000Z │ SUCCESS │   └─ params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}
2021-07-20T17:57:40.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:40.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...
2021-07-20T17:57:50.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Limit, side: sell, amount: 5, price: 141.67, params: {undefined: 141.67}}
2021-07-20T17:57:50.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ type:   Limit
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ side:   sell
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ price:  141.67
2021-07-20T17:57:50.000Z │ SUCCESS │   └─ params: {undefined: 141.67}
2021-07-20T17:57:50.000Z │ NOTICE  │ Processed order queue: 3/3 order(s) submitted successfully.
2021-07-20T17:57:50.000Z │ NOTICE  │ Command Completed: Execution Time: 34.569 seconds`

thank you
