### ISSUE TITLE
FTX sell order failed

### ISSUE THREAD

**Issue by shimuldn** [CryptoMF/frostybot-js#72]
Hello,
Thanks for this simple bot.

Bot not able to sell order on FTX. May be instade of calculating how much crypto is there from the current balance, keep the quantity from the successful order and sell the same (After detecting the fee of course) Or may be a batter soluton.

```
2021-05-24T18:21:04.000Z │ DEBUG   │ Execute permission granted using standard permission set: trade:sell => [core, singleuser]
2021-05-24T18:21:04.000Z │ DEBUG   │ Fetched 0 pre-cached records from datasource exchange:positions
2021-05-24T18:21:04.000Z │ DEBUG   │ Fetched 2 pre-cached records from datasource exchange:balances
2021-05-24T18:21:04.000Z │ DEBUG   │ Current position size in USD: 0
2021-05-24T18:21:04.000Z │ DEBUG   │ Current available balance in USD: 98.12
2021-05-24T18:21:04.000Z │ DEBUG   │ Fetched 0 pre-cached records from datasource exchange:positions
2021-05-24T18:21:04.000Z │ DEBUG   │ Fetched 2 pre-cached records from datasource exchange:balances
2021-05-24T18:21:04.000Z │ DEBUG   │ The size of 99% has been converted to 97.15 ($98 balance x 0.99)
2021-05-24T18:21:04.000Z │ DEBUG   │ Fetched 0 pre-cached records from datasource exchange:positions
2021-05-24T18:21:04.000Z │ DEBUG   │ Order size provided in USD (USD size)
2021-05-24T18:21:04.000Z │ NOTICE  │ Current position USD size is: USD 0
2021-05-24T18:21:04.000Z │ NOTICE  │ Target position USD size is: USD -97.15
2021-05-24T18:21:04.000Z │ NOTICE  │ Order required to reach target: Sell => USD 97.15
2021-05-24T18:21:04.000Z │ DEBUG   │ Size provided in USD on a stablecoin-paired asset. Using USD size as quote size.
2021-05-24T18:21:04.000Z │ DEBUG   │ Exchange uses base sizing. Order size converted to BNB (0.28273415422762505)
2021-05-24T18:21:04.000Z │ NOTICE  │ Order added to queue: {symbol: BNB/USD, type: market, side: sell, amount: 0.28, params: {}}
2021-05-24T18:21:04.000Z │ NOTICE  │ Order added to queue:
2021-05-24T18:21:04.000Z │ NOTICE  │   ├─ symbol: BNB/USD
2021-05-24T18:21:04.000Z │ NOTICE  │   ├─ type:   market
2021-05-24T18:21:04.000Z │ NOTICE  │   ├─ side:   sell
2021-05-24T18:21:04.000Z │ NOTICE  │   └─ amount: 0.28
2021-05-24T18:21:05.000Z │ WARNING │ Unhandled Exception: InsufficientFunds: ftx {"success":false,"error":"Not enough balances"} (::)
2021-05-24T18:21:05.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'type' of undefined at frostybot_queue_module.submit (mod.queue.js:111:36))
2021-05-24T18:21:05.000Z │ NOTICE  │ Command Completed: Execution Time: 0.393 seconds
```

**Comment by CryptoMF** [comment]
Hi

You could use the base= parameter in your command instead of size= to trade
on the base (BNB) size of the position

**Comment by shimuldn** [comment]
Please note: FTX spot order.

`frostybot trade:ftxbnb:sell symbol=BNB/USD base=BNB price=329`

```
{
  "result": "error",
  "message": "Could not determine order size: {sizing: base, base: false, quote: null, price: 329}",
  "type": "Object",
  "data": {},
  "messages": [
    "2021-05-29 21:56:00 | NOTICE  | Command Parameters: {command: trade:sell, symbol: BNB/USD, base: BNB, price: 329, stub: ftxbnb}",
    "2021-05-29 21:56:00 | DEBUG   | Execute permission granted using standard permission set: trade:sell => [core, singleuser]",
    "2021-05-29 21:56:00 | DEBUG   | Fetched 0 pre-cached records from datasource exchange:positions",
    "2021-05-29 21:56:00 | DEBUG   | Fetched 2 pre-cached records from datasource exchange:balances",
    "2021-05-29 21:56:00 | DEBUG   | Current position size in USD: 0",
    "2021-05-29 21:56:00 | DEBUG   | Current available balance in USD: 1628.03",
    "2021-05-29 21:56:00 | DEBUG   | Fetched 0 pre-cached records from datasource exchange:positions",
    "2021-05-29 21:56:00 | DEBUG   | Order size provided in BNB (base size)",
    "2021-05-29 21:56:00 | NOTICE  | Current position base size is: BNB 0",
    "2021-05-29 21:56:00 | NOTICE  | Target position base size is: BNB NaN",
    "2021-05-29 21:56:00 | NOTICE  | Order required to reach target: Sell => BNB NaN",
    "2021-05-29 21:56:00 | DEBUG   | Exchange uses base sizing. Order size converted to BNB (NaN)",
    "2021-05-29 21:56:00 | ERROR   | Could not determine order size: {sizing: base, base: false, quote: null, price: 329}",
    "2021-05-29 21:56:00 | ERROR   | Order size is smaller than the minimum size supported by the exchange",
    "2021-05-29 21:56:00 | NOTICE  | Order Completed: Execution Time: 0.088 seconds",
    "2021-05-29 21:56:00 | NOTICE  | Command Completed: Execution Time: 0.092 seconds"
  ]
}
```

`frostybot trade:ftxbnb:sell symbol=BNB/USD base=BNB price=329`

```
{
  "result": "error",
  "message": "You do not currently have a position on BNB/USD",
  "type": "Object",
  "data": {},
  "messages": [
    "2021-05-29 21:58:51 | NOTICE  | Command Parameters: {command: trade:close, symbol: BNB/USD, base: BNB, price: 329, stub: ftxbnb}",
    "2021-05-29 21:58:51 | DEBUG   | Execute permission granted using standard permission set: trade:close => [core, singleuser]",
    "2021-05-29 21:58:52 | NOTICE  | 0 Order(s) cancelled",
    "2021-05-29 21:58:52 | DEBUG   | Fetched 0 pre-cached records from datasource exchange:positions",
    "2021-05-29 21:58:52 | ERROR   | You do not currently have a position on BNB/USD",
    "2021-05-29 21:58:52 | NOTICE  | Order Completed: Execution Time: 0.986 seconds",
    "2021-05-29 21:58:52 | NOTICE  | Command Completed: Execution Time: 0.989 seconds"
  ]
}
```
<img width="1038" alt="Screenshot 2021-05-29 at 10 00 17 PM" src="https://user-images.githubusercontent.com/12117121/120077697-4d228700-c0c9-11eb-9275-c2eb694e4b07.png">

**Comment by CryptoMF** [comment]
The base parameter should be the amount of BNB, not the symbol BNB. Please
check the wiki for full documentation of all the parameters available.

**Comment by shimuldn** [comment]
`frostybot trade:ftxbnb:sell symbol=BNB/USD base=1 price=329` Work.

Is there any way to sell all the available BNB without specifying the amount?

**Comment by CryptoMF** [comment]
You could use the close command:

frostybot trade:ftxbnb:close symbol=BNB/USD

**Comment by shimuldn** [comment]
I have balance is BNB.
After `frostybot trade:ftxbnb:close symbol=BNB/USD`
```
    "2021-05-31 14:42:12 | DEBUG   | Execute permission granted using standard permission set: trade:close => [core, singleuser]",
    "2021-05-31 14:42:13 | WARNING | Unhandled Exception: ExchangeError: binance fetchOpenOrders WARNING: fetching open orders without specifying a symbol is rate-limited to one call per 729 seconds. Do not call this method frequently to avoid ban. Set binance.options[\"warnOnFetchOpenOrdersWithoutSymbol\"] = false to suppress this warning message. at binance.fetchOpenOrders (binance.js:2130:19))",
    "2021-05-31 14:42:13 | ERROR   | There was an error cancelling orders",
    "2021-05-31 14:42:13 | DEBUG   | Fetched 0 pre-cached records from datasource exchange:positions",
    "2021-05-31 14:42:13 | ERROR   | You do not currently have a position on BNB/USD",
    "2021-05-31 14:42:13 | NOTICE  | Order Completed: Execution Time: 0.876 seconds",
    "2021-05-31 14:42:13 | NOTICE  | Command Completed: Execution Time: 0.878 seconds"
```

**Comment by shimuldn** [comment]
Spot trading.
Using `development branch` for web-socket


`frostybot trade:ftxbnb:sell symbol=BNB/USD size=50%` or `100%` only work when there is no other balance.
When there is some other balance ie EUR or any crypto frosty calculate all the balance as USD for buying and base currency for selling. Result fail to sell.

Please implement the function with batter calculation
 * Buy or Sell balance with `%` ie.`size=100%` or `size=70%` Currently having issue if there is any other balance ie USDT, EUR or crypto.
 * `frostybot trade:ftxbnb:close symbol=BNB/USD` to sell `all` the BNB for spot trading.

Thank you
