### ISSUE TITLE
Incorrect symbol conversion + 'toLowerCase' bug

### ISSUE THREAD

**Issue by cryptomius** [CryptoMF/frostybot-js#86]
I seem to be getting a weird symbol translation from BTC-PERP & BTC-1231 on FTX to TRX/USD.
Also, I get a warning on toLowerCase of undefined.

2021-07-12T11:30:06.000Z │ NOTICE  │ Command Parameters: {command: trade:stoploss, stub: ftx, symbol: BTC-1231, stoptrigger: 35449.35, reduce: true}
2021-07-12T11:30:06.000Z │ NOTICE  │ Command Parameters:
2021-07-12T11:30:06.000Z │ NOTICE  │   ├─ command:     trade:stoploss
2021-07-12T11:30:06.000Z │ NOTICE  │   ├─ stub:        ftx
2021-07-12T11:30:06.000Z │ NOTICE  │   ├─ symbol:      BTC-1231
2021-07-12T11:30:06.000Z │ NOTICE  │   ├─ stoptrigger: 35449.35
2021-07-12T11:30:06.000Z │ NOTICE  │   └─ reduce:      true
2021-07-12T11:30:06.000Z │ DEBUG   │ Execute permission granted using standard permission set: trade:stoploss => [core, singleuser]
2021-07-12T11:30:08.000Z │ DEBUG   │ **Converting using symbol: TRX/USD**
2021-07-12T11:30:09.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'toLowerCase' of undefined at frostybot_trade_module.potential_position (mod.trade.js:1226:41)
2021-07-12T11:30:09.000Z │ NOTICE  │ Command Completed: Execution Time: 3.005 seconds

**Comment by CryptoMF** [comment]
Hi Shannon

Is this on the stable or development branch?

Regards

**Comment by cryptomius** [comment]
I believe it is the stable - I used Docker on Azure via the link on the Wiki:
https://github.com/CryptoMF/frostybot-js/wiki/System-Requirements

**Comment by CryptoMF** [comment]
Ok, give me a moment to set it up and I'll test and get back to you.

**Comment by cryptomius** [comment]
It doesn't seem to matter if the symbol is mapped to itself (just exploring options here) :-) 

2021-07-12T12:54:37.000Z │ SUCCESS │ **Added symbol mapping: ftx: BTC-1231 => BTC-1231**
2021-07-12T12:54:37.000Z │ DEBUG   │ Retrieved symbol mapping: ftx: BTC-1231 => BTC-1231
2021-07-12T12:54:37.000Z │ NOTICE  │ Command Completed: Execution Time: 0.002 seconds
2021-07-12T13:30:07.000Z │ NOTICE  │ Command Parameters: {command: trade:stoploss, stub: ftx, symbol: BTC-1231, stoptrigger: 35095.1, reduce: true}
2021-07-12T13:30:07.000Z │ NOTICE  │ Command Parameters:
2021-07-12T13:30:07.000Z │ NOTICE  │   ├─ command:     trade:stoploss
2021-07-12T13:30:07.000Z │ NOTICE  │   ├─ stub:        ftx
2021-07-12T13:30:07.000Z │ NOTICE  │   ├─ symbol:      BTC-1231
2021-07-12T13:30:07.000Z │ NOTICE  │   ├─ stoptrigger: 35095.1
2021-07-12T13:30:07.000Z │ NOTICE  │   └─ reduce:      true
2021-07-12T13:30:07.000Z │ DEBUG   │ Execute permission granted using standard permission set: trade:stoploss => [core, singleuser]
2021-07-12T13:30:07.000Z │ NOTICE  │ **Using symbol mapping: ftx: BTC-1231 => BTC-1231**
2021-07-12T13:30:10.000Z │ DEBUG   │ **Converting using symbol: TRX/USD**
2021-07-12T13:30:11.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'toLowerCase' of undefined at frostybot_trade_module.potential_position (mod.trade.js:1226:41)
2021-07-12T13:30:11.000Z │ NOTICE  │ Command Completed: Execution Time: 3.46 seconds

**Comment by CryptoMF** [comment]
Taking a look at the Unhandled Exception: TypeError in your log, it's working on a variable that specified the buy or sell side of the order, so it appears as though it has been unable to determine the which side to place the order. 

Do you have an open position for this stoploss you're trying to place?

**Comment by cryptomius** [comment]
Yes I have a short position open at the moment and using Frostybot to set the buy stoploss. 

What I'm doing currently is entering into a position using FTX via their website UI with an initial stop market trigger order and then using a Tradingview indicator (supertrend) to pass the stoploss command through to Frostybot via tradingview alert webhook. 

`trade:stoploss stub=ftx symbol=BTC-1231 stoptrigger={{plot_3}} reduce=true` 
...where `{{plot_3}}` is the indicator's down-trend plot.

I can see this working correctly for SOL-PERP but not BTC-PERP or BTC-1231 despite the identical setup.

I think I'll try running it locally rather than in the cloud so I can put some extra logging in?

**Comment by CryptoMF** [comment]
Why not just add the stop params to the short order?

stub:short size=1000 stoptrigger=+2% symbol=BTCUSDT

**Comment by cryptomius** [comment]
Having a fixed increment or % is a quick way of getting stopped out upon a minor retracement. For trend trading I want to be in the trade as long as it is trending downward so I use Supertrend to determine how far from the price action to set my stop to avoid getting caught in the usual price volatility.

**Comment by cryptomius** [comment]
Hey @CryptoMF I've been using it actively tonight on BTC-PERP and it's been working well. Perhaps it was just a glitch in the matrix and the TRX/USD reference is a separate matter. On a local copy the TRX/USD reference came up still however it didn't block stoploss orders. I tried logging several points but didn't get to the root of where the reference came from. I'll re-open issue if it resurfaces or I can track it down. Thanks for your willingness to help :-)
