### ISSUE TITLE
Rate limit error on Bitmex

### ISSUE THREAD

**Issue by alperoguz** [CryptoMF/frostybot-js#88]
Hello,

I was commented this in #67. But, it's already closed. You can delete this issue and re-open #67 if you like. thank you

I faced this error on Bitmex testnet today. I was testing only with one small LTCUSD order.

2021-07-20T17:57:40.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:40.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...

You can find full log below.

`2021-07-20T17:57:16.000Z │ NOTICE  │ Whitelist verification is enabled
2021-07-20T17:57:16.000Z │ NOTICE  │ API Access Granted: 127.0.0.1 is whitelisted
2021-07-20T17:57:16.000Z │ NOTICE  │ Command Parameters: {command: trade:long, symbol: LTC/USD, size: 5, stub: bitmex_testnet}
2021-07-20T17:57:16.000Z │ NOTICE  │ Command Parameters:
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ command: trade:long
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ symbol:  LTC/USD
2021-07-20T17:57:16.000Z │ NOTICE  │   ├─ size:    5
2021-07-20T17:57:16.000Z │ NOTICE  │   └─ stub:    bitmex_testnet
2021-07-20T17:57:19.000Z │ NOTICE  │ Current position USD size is: USD 0
2021-07-20T17:57:19.000Z │ NOTICE  │ Target position USD size is: USD 5
2021-07-20T17:57:19.000Z │ NOTICE  │ Order required to reach target: Buy => USD 5
2021-07-20T17:57:21.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Market, side: buy, amount: 5, params: {execInst: }}
2021-07-20T17:57:21.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ type:   Market
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ side:   buy
2021-07-20T17:57:21.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:21.000Z │ NOTICE  │   └─ params: {execInst: }
2021-07-20T17:57:24.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:25.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Stop, side: sell, amount: 5, params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}}
2021-07-20T17:57:25.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ type:   Stop
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ side:   sell
2021-07-20T17:57:25.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:25.000Z │ NOTICE  │   └─ params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}
2021-07-20T17:57:28.000Z │ NOTICE  │ Order added to queue: {symbol: LTC/USD, type: Limit, side: sell, amount: 5, price: 141.67, params: {undefined: 141.67}}
2021-07-20T17:57:28.000Z │ NOTICE  │ Order added to queue:
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ symbol: LTC/USD
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ type:   Limit
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ side:   sell
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ amount: 5
2021-07-20T17:57:28.000Z │ NOTICE  │   ├─ price:  141.67
2021-07-20T17:57:28.000Z │ NOTICE  │   └─ params: {undefined: 141.67}
2021-07-20T17:57:29.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:29.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:29.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:29.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...
2021-07-20T17:57:39.000Z │ WARNING │ Retrying order (Retry 1 of 5)...
2021-07-20T17:57:39.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Market, side: buy, amount: 5, params: {execInst: }}
2021-07-20T17:57:39.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ type:   Market
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ side:   buy
2021-07-20T17:57:39.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:39.000Z │ SUCCESS │   └─ params: {execInst: }
2021-07-20T17:57:40.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Stop, side: sell, amount: 5, params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}}
2021-07-20T17:57:40.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ type:   Stop
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ side:   sell
2021-07-20T17:57:40.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:40.000Z │ SUCCESS │   └─ params: {undefined: 106.25, stopPx: 106.25, execInst: ReduceOnly,MarkPrice}
2021-07-20T17:57:40.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order submission failed:
2021-07-20T17:57:40.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-20T17:57:40.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...
2021-07-20T17:57:50.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: LTC/USD, type: Limit, side: sell, amount: 5, price: 141.67, params: {undefined: 141.67}}
2021-07-20T17:57:50.000Z │ SUCCESS │ Order submitted successfully:
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ symbol: LTC/USD
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ type:   Limit
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ side:   sell
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ amount: 5
2021-07-20T17:57:50.000Z │ SUCCESS │   ├─ price:  141.67
2021-07-20T17:57:50.000Z │ SUCCESS │   └─ params: {undefined: 141.67}
2021-07-20T17:57:50.000Z │ NOTICE  │ Processed order queue: 3/3 order(s) submitted successfully.
2021-07-20T17:57:50.000Z │ NOTICE  │ Command Completed: Execution Time: 34.569 seconds`

thank you

_Originally posted by @alperoguz in https://github.com/CryptoMF/frostybot-js/issues/67#issuecomment-883717672_

**Comment by shimuldn** [comment]
Try development branch.
`git checkout development`

**Comment by alperoguz** [comment]
> Try development branch.
> `git checkout development`

FrostyAF on Discord said that Bitmex not supported on development branch.

I think my server banned on Bitmex now. Orders don't work anymore from Tradingview alert or from server command line.

**Comment by alperoguz** [comment]
Meanwhile, standart temporary ban on Bitmex is 1 hour.

Bitmex support replied as:

```
According to our information, most of the errors had a 429 code, which means API query quota exceeding. 

Please find more information about working with the API here:

https://www.bitmex.com/app/restAPI#Request-Rate-Limits

You could have received an hour-long IP ban from our DDOS protection system because your script
possibly was ignoring error messages. 

In order to avoid this situation in the future, please implement an error handling in your code, which
prevents your software from sending multiple error-returning requests in a row. 

We also recommend the usage of our official API connectors.

https://github.com/BitMEX/api-connectors
```
