### ISSUE TITLE
Using close & cancelall for previous position and open a new one in same signal

### ISSUE THREAD

**Issue by alperoguz** [CryptoMF/frostybot-js#89]
Hello,

First, thank you for this great work guys.

I have a question about closing a position, cleaning old orders and opening a new one.

Imagine that, I have an active short position and also some orders. But, if Frosty receive a long signal from Tradingview, I need to cancel all TP, SL, Limit orders and close current short position before try to open a new position.

I tried to use these commands in CLI. All of them work great when I run in two commands like this:

```
frostybot trade:bitmex_testnet:close size=100% trade:bitmex_testnet:cancelall symbol=BTC/USD
frostybot trade:bitmex_testnet:leverage=2:type=isolated trade:bitmex_testnet:long symbol=BTC/USD size=500
```

But, when I put them into one big command, cancelall looks prevent other commands. Is this syntax correct?

```
frostybot trade:bitmex_testnet:close size=100% trade:bitmex_testnet:cancelall trade:bitmex_testnet:leverage=2:type=isolated trade:bitmex_testnet:long size=1000 symbol=BTC/USD
```

I tried as one big command, because even I use as two lines in Tradingiview alert. It looks behave same with one big command. Closing position, cancelling orders, but can't open the new position and can't put new orders:

My Tradingview long alert:

```
trade:bitmex_testnet:close size=100% trade:bitmex_testnet:cancelall symbol=BTC/USD
trade:bitmex_testnet:leverage=2:type=isolated trade:bitmex_testnet:long symbol=BTC/USD size=1000
```

You can find entire log here:

```
2021-07-21T07:18:12.000Z │ NOTICE  │ Whitelist verification is enabled
2021-07-21T07:18:12.000Z │ NOTICE  │ API Access Granted: 127.0.0.1 is whitelisted
2021-07-21T07:18:12.000Z │ NOTICE  │ Command Parameters: {command: trade:close, size: 100%, trade:bitmex_testnet:cancelall: false, symbol: BTC/USD, stub: bitmex_testnet}
2021-07-21T07:18:12.000Z │ NOTICE  │ Command Parameters:
2021-07-21T07:18:12.000Z │ NOTICE  │   ├─ command:                        trade:close
2021-07-21T07:18:12.000Z │ NOTICE  │   ├─ size:                           100%
2021-07-21T07:18:12.000Z │ NOTICE  │   ├─ symbol:                         BTC/USD
2021-07-21T07:18:12.000Z │ NOTICE  │   └─ stub:                           bitmex_testnet
2021-07-21T07:18:12.000Z │ DEBUG   │ Execute permission granted using standard permission set: trade:close => [core, singleuser]
2021-07-21T07:18:14.000Z │ NOTICE  │ 2 Order(s) cancelled
2021-07-21T07:18:15.000Z │ DEBUG   │ Converting using symbol: BTC/USD
2021-07-21T07:18:15.000Z │ DEBUG   │ Current position size in USD: 501.49
2021-07-21T07:18:15.000Z │ DEBUG   │ Current available balance in USD: 9711.74
2021-07-21T07:18:16.000Z │ DEBUG   │ The size of 100% has been converted to 501.50 ($501 position x 1)
2021-07-21T07:18:16.000Z │ DEBUG   │ The closing order size of 501.5 exceeds your current position, adjusting order size to 501.49102431250003.
2021-07-21T07:18:16.000Z │ DEBUG   │ Order size provided in USD (USD size)
2021-07-21T07:18:16.000Z │ NOTICE  │ Current position USD size is: USD -501.49102431250003
2021-07-21T07:18:16.000Z │ NOTICE  │ Target position USD size is: USD 0
2021-07-21T07:18:16.000Z │ NOTICE  │ Order required to reach target: Buy => USD 501.49102431250003
2021-07-21T07:18:17.000Z │ DEBUG   │ Size provided in USD on a stablecoin-paired asset. Using USD size as quote size.
2021-07-21T07:18:17.000Z │ DEBUG   │ Exchange uses quote sizing. Order size converted to USD (501.49102431250003)
2021-07-21T07:18:18.000Z │ NOTICE  │ Order added to queue: {symbol: BTC/USD, type: Market, side: buy, amount: 500, params: {execInst: }}
2021-07-21T07:18:18.000Z │ NOTICE  │ Order added to queue:
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ symbol: BTC/USD
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ type:   Market
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ side:   buy
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ amount: 500
2021-07-21T07:18:18.000Z │ NOTICE  │   └─ params: {execInst: }
2021-07-21T07:18:18.000Z │ DEBUG   │ Order submitted to exchange: ccc8f67c-8f38-493c-8e82-578dd052eadd
2021-07-21T07:18:18.000Z │ SUCCESS │ Order submitted successfully: {stub: bitmex_testnet, symbol: BTC/USD, type: Market, side: buy, amount: 500, params: {execInst: }}
2021-07-21T07:18:18.000Z │ SUCCESS │ Order submitted successfully:
2021-07-21T07:18:18.000Z │ SUCCESS │   ├─ stub:   bitmex_testnet
2021-07-21T07:18:18.000Z │ SUCCESS │   ├─ symbol: BTC/USD
2021-07-21T07:18:18.000Z │ SUCCESS │   ├─ type:   Market
2021-07-21T07:18:18.000Z │ SUCCESS │   ├─ side:   buy
2021-07-21T07:18:18.000Z │ SUCCESS │   ├─ amount: 500
2021-07-21T07:18:18.000Z │ SUCCESS │   └─ params: {execInst: }
2021-07-21T07:18:18.000Z │ NOTICE  │ Processed order queue: 1/1 order(s) submitted successfully.
2021-07-21T07:18:18.000Z │ NOTICE  │ Command Completed: Execution Time: 6.587 seconds
2021-07-21T07:18:18.000Z │ NOTICE  │ Command Parameters: {command: trade:long, trade:bitmex_testnet:leverage: 2:type, symbol: BTC/USD, size: 500, stub: bitmex_testnet}
2021-07-21T07:18:18.000Z │ NOTICE  │ Command Parameters:
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ command:                       trade:long
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ trade:bitmex_testnet:leverage: 2:type
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ symbol:                        BTC/USD
2021-07-21T07:18:18.000Z │ NOTICE  │   ├─ size:                          500
2021-07-21T07:18:18.000Z │ NOTICE  │   └─ stub:                          bitmex_testnet
2021-07-21T07:18:18.000Z │ DEBUG   │ Execute permission granted using standard permission set: trade:long => [core, singleuser]
2021-07-21T07:18:20.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-21T07:18:20.000Z │ DEBUG   │ Current position size in USD: 501.49
2021-07-21T07:18:20.000Z │ DEBUG   │ Current available balance in USD: NaN
2021-07-21T07:18:21.000Z │ WARNING │ The provided order sizing results in a position flip from short to long
2021-07-21T07:18:21.000Z │ DEBUG   │ Order size provided in USD (USD size)
2021-07-21T07:18:21.000Z │ NOTICE  │ Current position USD size is: USD -501.49102431250003
2021-07-21T07:18:21.000Z │ NOTICE  │ Target position USD size is: USD 500
2021-07-21T07:18:21.000Z │ NOTICE  │ Order required to reach target: Buy => USD 1001.4910243125
2021-07-21T07:18:21.000Z │ DEBUG   │ Size provided in USD on a stablecoin-paired asset. Using USD size as quote size.
2021-07-21T07:18:21.000Z │ DEBUG   │ Exchange uses quote sizing. Order size converted to USD (1001.4910243125)
2021-07-21T07:18:21.000Z │ NOTICE  │ Order added to queue: {symbol: BTC/USD, type: Market, side: buy, amount: 1000, params: {execInst: }}
2021-07-21T07:18:21.000Z │ NOTICE  │ Order added to queue:
2021-07-21T07:18:21.000Z │ NOTICE  │   ├─ symbol: BTC/USD
2021-07-21T07:18:21.000Z │ NOTICE  │   ├─ type:   Market
2021-07-21T07:18:21.000Z │ NOTICE  │   ├─ side:   buy
2021-07-21T07:18:21.000Z │ NOTICE  │   ├─ amount: 1000
2021-07-21T07:18:21.000Z │ NOTICE  │   └─ params: {execInst: }
2021-07-21T07:18:22.000Z │ DEBUG   │ Stoploss not provided, using default stoploss: bitmex_testnet:defstoptrigger=10%
2021-07-21T07:18:23.000Z │ DEBUG   │ Current position and open orders calculated to potential position: {price: 31510.615856676628, base: 0.04761159060803044, quote: 1500.270541975, sizing: quote, side: buy, amount: 1500.270541975, totals: {position: 500.270541975, orders: false, queue: 1000}}
2021-07-21T07:18:23.000Z │ DEBUG   │ Current position and open orders calculated to potential position:
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ price:  31510.615856676628
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ base:   0.04761159060803044
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ quote:  1500.270541975
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ sizing: quote
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ side:   buy
2021-07-21T07:18:23.000Z │ DEBUG   │   ├─ amount: 1500.270541975
2021-07-21T07:18:23.000Z │ DEBUG   │   └─ totals: {position: 500.270541975, orders: false, queue: 1000}
2021-07-21T07:18:23.000Z │ DEBUG   │ Converted relative price: 31510.5-10% => 28359.5
2021-07-21T07:18:24.000Z │ DEBUG   │ Exchange uses quote sizing. Order size converted to USD (1500.270541975)
2021-07-21T07:18:24.000Z │ NOTICE  │ Command Parameters: {command: user:login, email: alperoguz@gmail.com, password: ********, token2fa: }
2021-07-21T07:18:24.000Z │ NOTICE  │ Command Parameters:
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ command:  user:login
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ email:    alperoguz@gmail.com
2021-07-21T07:18:24.000Z │ NOTICE  │   └─ password: ********
2021-07-21T07:18:24.000Z │ DEBUG   │ Execute permission granted using standard permission set: user:login => [remote]
2021-07-21T07:18:24.000Z │ SUCCESS │ User authenticated successfully: alperoguz@gmail.com
2021-07-21T07:18:24.000Z │ NOTICE  │ Command Completed: Execution Time: 0.003 seconds
2021-07-21T07:18:24.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-21T07:18:24.000Z │ NOTICE  │ Order added to queue: {symbol: BTC/USD, type: Stop, side: sell, amount: 1500, params: {undefined: 28359.5, stopPx: 28359.5, execInst: ReduceOnly,MarkPrice}}
2021-07-21T07:18:24.000Z │ NOTICE  │ Order added to queue:
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ symbol: BTC/USD
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ type:   Stop
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ side:   sell
2021-07-21T07:18:24.000Z │ NOTICE  │   ├─ amount: 1500
2021-07-21T07:18:24.000Z │ NOTICE  │   └─ params: {undefined: 28359.5, stopPx: 28359.5, execInst: ReduceOnly,MarkPrice}
2021-07-21T07:18:24.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-21T07:18:25.000Z │ DEBUG   │ Take profit size not provided, using default take profit size: bitmex_testnet:defprofitsize=100%
2021-07-21T07:18:25.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-21T07:18:25.000Z │ DEBUG   │ Take profit not provided, using default take profit: bitmex_testnet:defprofittrigger=30%
2021-07-21T07:18:25.000Z │ WARNING │ Unhandled Exception: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}} at bitmex.handleErrors (bitmex.js:1629:19)
2021-07-21T07:18:26.000Z │ DEBUG   │ Current position and open orders calculated to potential position: {price: 31536.25, base: 0.03170954060803044, quote: 1000, sizing: quote, side: buy, amount: 1000, totals: {position: false, orders: false, queue: 1000}}
2021-07-21T07:18:26.000Z │ DEBUG   │ Current position and open orders calculated to potential position:
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ price:  31536.25
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ base:   0.03170954060803044
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ quote:  1000
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ sizing: quote
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ side:   buy
2021-07-21T07:18:26.000Z │ DEBUG   │   ├─ amount: 1000
2021-07-21T07:18:26.000Z │ DEBUG   │   └─ totals: {position: false, orders: false, queue: 1000}
2021-07-21T07:18:26.000Z │ DEBUG   │ Converted relative price: 31536.5+30% => 40997.5
2021-07-21T07:18:27.000Z │ DEBUG   │ Exchange uses quote sizing. Order size converted to USD (1000)
2021-07-21T07:18:28.000Z │ NOTICE  │ Order added to queue: {symbol: BTC/USD, type: Limit, side: sell, amount: 1000, price: 40997.5, params: {undefined: 40997.5}}
2021-07-21T07:18:28.000Z │ NOTICE  │ Order added to queue:
2021-07-21T07:18:28.000Z │ NOTICE  │   ├─ symbol: BTC/USD
2021-07-21T07:18:28.000Z │ NOTICE  │   ├─ type:   Limit
2021-07-21T07:18:28.000Z │ NOTICE  │   ├─ side:   sell
2021-07-21T07:18:28.000Z │ NOTICE  │   ├─ amount: 1000
2021-07-21T07:18:28.000Z │ NOTICE  │   ├─ price:  40997.5
2021-07-21T07:18:28.000Z │ NOTICE  │   └─ params: {undefined: 40997.5}
2021-07-21T07:18:28.000Z │ WARNING │ Order submission failed: DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-21T07:18:28.000Z │ WARNING │ Order submission failed:
2021-07-21T07:18:28.000Z │ WARNING │ DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
2021-07-21T07:18:28.000Z │ WARNING │ Order failed, waiting 10 seconds before retrying...
2021-07-21T07:18:38.000Z │ WARNING │ Retrying order (Retry 1 of 5)...
2021-07-21T07:18:38.000Z │ WARNING │ Unhandled Exception: TypeError: Cannot read property 'replace' of undefined at frostybot_output_module.exception (mod.output.js:202:43)
2021-07-21T07:18:38.000Z │ NOTICE  │ Command Completed: Execution Time: 19.635 seconds
```

thank you in advance

**Comment by alperoguz** [comment]
Frosty AF helped me on Discord and using this kind of command solved this issue:

`trade:bitmex_testnet:leverage=2:type=isolated trade:bitmex_testnet:long symbol=BTC/USD size=1000 cancelall=true stoptrigger=-10% profittrigger=+5% reduce=true`
